base_url = "https://jobl.dev"
title = "JOBL"
description = "A TOML-based resume format"
compile_sass = false
minify_html = false
build_search_index = false

[markdown]
highlight_code = true
highlight_theme = "base16-ocean-dark"
